apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dj-jazz-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
    configuration.konghq.com: do-not-preserve-host
spec:
  rules:
  - http:
      paths:
        - path: /dj/jazz
          backend:
            serviceName: jazz
            servicePort: 9080
